apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loginapp-argo-application
  namespace: argo

spec:
  project: default

  source:
    repoURL: https://github.com/nilupabatawala/loginapp.git
    target: HEAD
    path: manifests
  destination: 
    server: https://kubernetes.default.svc
    namespace: app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated: 
      selfHeal: true
      prune: true