apiVersion: v1
kind: Secret
metadata:
  name: helm-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSI0MjQ0MTYyMDc0MDYuZGtyLmVjci5ldS1ub3J0aC0xLmFtYXpvbmF3cy5jb20iOiB7fSwKCQkiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjoge30KCX0sCgkiY3JlZHNTdG9yZSI6ICJkZXNrdG9wIiwKCSJjdXJyZW50Q29udGV4dCI6ICJkZWZhdWx0Igp9